### ISSUE TITLE
EPIC: Expand and Consolidate documentation

### ISSUE THREAD

**Issue by seanpearsonuk** [ansys/pyfluent#2412]
- [X] ensure that documentation fully covers all PyFluent-* features 
- [X] maintain cheatsheet properly so that it always gives a full, broad and up-to-date summary over PyFluent functionality https://github.com/ansys/pyfluent/pull/3481
- [X] link to the cheatsheet from the main doc OR rather just start from scratch! https://github.com/ansys/pyfluent/pull/3481
- [ ] optionally create a PyFluent-visualization cheatsheet
Good example: https://matplotlib.org/cheatsheets/_images/cheatsheets-1.png
Specific, additional issues:
- [X] add a user-guide section, fully detailing what all the session types are #2956
- [X] Consider moving much doc from API Ref to user guide #2957
- [x] #3725
- [X] API reference simply exposes the public interfaces based on the package hierarchy #3109

**Comment by mkundu1** [comment]
The following dcumentation aspects of Python sources should be looked into:
1. Missing or incomplete docstrings
2. Missing typehints
3. Missing exception specification (serach for `disable=missing-raises-doc` in code)
A lot of these can be captured by enbaling linter options (e.g. enabling `missing-param-doc` in the docparams pylint extension shows all missing parameter declaration).

**Comment by seanpearsonuk** [comment]
@hpohekar to look into 1 and 3 above

**Comment by mkundu1** [comment]
Related: https://github.com/ansys-internal/pyansys-quarto-cheatsheet

**Comment by seanpearsonuk** [comment]
The cheatsheet part is still outstanding. Also note the points made by @mkundu1  above.

**Comment by hpohekar** [comment]
@seanpearsonuk I'm looking into cheat sheet part. https://github.com/ansys/pyfluent/issues/3461
